[build]
builder = "nixpacks"

[deploy]
startCommand = "node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 2

[env]
NODE_ENV = "production"
PORT = "8080"
HTTPS = "true"
SESSION_SECRET = "ash-educational-production-secret-key-2024"
