[build]
builder = "nixpacks"

[deploy]
startCommand = "node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 2

[env]
NODE_ENV = "production"
PORT = "8080"
HTTPS = "true"
JWT_SECRET = "ash-jwt-secret-key-2024-production"
